Arguments for the Clinical Trials Meta Analysis Task Evaluator:
Task:         outcome_type
Output Path:  /scratch/yun.hy/llm-meta-analysis/evaluation/outputs/outcome_type/gemma7B_outcome_type_test_output_20240326-12:00:55.json
Metrics Path: /scratch/yun.hy/llm-meta-analysis/evaluation/metrics/outcome_type/

Traceback (most recent call last):
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 176, in <module>
    task_evaluator.run_evaluation()
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 139, in run_evaluation
    metrics = self.metrics_calculator.calculate_metrics(self.data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/calculate_metrics.py", line 256, in calculate_metrics
    metrics["outcome_type_f_score"] = self.__calculate_f_score(data)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/calculate_metrics.py", line 71, in __calculate_f_score
    "f1_score_unknown": f1_scores[2]
                        ~~~~~~~~~^^^
IndexError: list index out of range
