Arguments for the Clinical Trials Meta Analysis Task Evaluator:
Task:         outcome_type
Output Path:  /scratch/yun.hy/llm-meta-analysis/evaluation/outputs/outcome_type/gpt4_outcome_type_test_output_20240325-11:55:44.json
Metrics Path: /scratch/yun.hy/llm-meta-analysis/evaluation/metrics/outcome_type/

Metrics for the task:
{
    "number_of_model_unknowns": {
        "outcome_type": 155,
        "total": 155
    },
    "number_of_reference_unknowns": {
        "outcome_type": 0,
        "total": 0
    },
    "exact_match_accuracy": {
        "outcome_type": 0.7134146341463414,
        "total": 0.7134146341463414
    },
    "exact_match_accuracy_remove_unknowns": {
        "outcome_type": 0.9341317365269461,
        "total": 0.9341317365269461
    },
    "partial_match_accuracy": {
        "partial_match_accuracy_1": 0.7134146341463414
    },
    "partial_match_accuracy_remove_unknowns": {
        "partial_match_accuracy_1": 0.9341317365269461
    },
    "outcome_type_f_score": {
        "outcome_type": {
            "f1_score_binary": 0.7354838709677418,
            "f1_score_continuous": 0.8358913813459268,
            "f1_score_unknown": 0.0
        }
    }
}
Arguments for the Clinical Trials Meta Analysis Task Evaluator:
Task:         binary_outcomes
Output Path:  /scratch/yun.hy/llm-meta-analysis/evaluation/outputs/binary_outcomes/gpt4_binary_outcomes_test_output_20240325-16:51:52.json
Metrics Path: /scratch/yun.hy/llm-meta-analysis/evaluation/metrics/binary_outcomes/


intervention:
    events: 14
  size: 49
comparator:
    events: 13
  size: 50

Traceback (most recent call last):
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 195, in <module>
    task_evaluator.run_evaluation()
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 151, in run_evaluation
    self.__preprocess_binary_outcomes_results()
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 75, in __preprocess_binary_outcomes_results
    output_dict = yaml.safe_load(model_output)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 2, column 1:
    intervention:
    ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 4, column 3:
      size: 49
      ^
Arguments for the Clinical Trials Meta Analysis Task Evaluator:
Task:         continuous_outcomes
Output Path:  /scratch/yun.hy/llm-meta-analysis/evaluation/outputs/continuous_outcomes/gpt4_continuous_outcomes_test_output_20240325-18:45:56.json
Metrics Path: /scratch/yun.hy/llm-meta-analysis/evaluation/metrics/continuous_outcomes


intervention:
    mean: x
    standard_deviation: x
  size: x
comparator:
    mean: x
    standard_deviation: x
  size: 15

Traceback (most recent call last):
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 195, in <module>
    task_evaluator.run_evaluation()
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 153, in run_evaluation
    self.__preprocess_continuous_outcomes_results()
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 122, in __preprocess_continuous_outcomes_results
    output_dict = yaml.safe_load(model_output)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/home/yun.hy/.conda/envs/llm-meta-analysis/lib/python3.11/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 2, column 1:
    intervention:
    ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 5, column 3:
      size: x
      ^
